reorder_imported_names = true
item_brace_style = "PreferSameLine"
fn_brace_style = "PreferSameLine"
fn_args_paren_newline = false
fn_args_density = "Compressed"
fn_arg_indent = "Tabbed"
fn_return_indent = "WithWhereClause"
where_indent = "Inherit"
where_layout = "Mixed"
where_density = "Compressed"
chain_base_indent = "Tabbed"
closure_block_indent_threshold = 2
