unstable_features = true

brace_style = "PreferSameLine"
fn_args_density = "Compressed"
imports_indent = "Block"
reorder_imports = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
