closure_block_indent_threshold = 2
fn_args_density = "Compressed"
fn_brace_style = "PreferSameLine"
fn_return_indent = "WithWhereClause"
item_brace_style = "PreferSameLine"
reorder_imports_in_group = true
where_density = "Compressed"
where_layout = "Mixed"
